# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: workspace
      POSTGRES_USER: workspace
      POSTGRES_PASSWORD: workspace
    ports:
      - "5432:5432"